sudo: false
language: python
dist: xenial  # required for Python >= 3.7

python:
  - "3.5"
  - "3.7"
# Multiple "Test" jobs seems to be required to run tests when
# conditional stages are added.  Run the CI with only one `python`
# entry above to reproduce this buggy behavior.  I'm not sure if this
# is a bug in Travis CI or in my config.

env:
  global:
    - TOXENV=py

before_install:
  - pip install --quiet "pip>=19.0"
  - pip install --quiet tox coveralls

script:
  - tox

after_success:
  - coveralls

notifications:
  email: false

jobs:
  include:

    - &check
      language: python
      env:
        - TOXENV=style
      os: linux
      python: "3.7"

    - <<: *check
      env:
        - TOXENV=type

    - <<: *check
      env:
        - TOXENV=packaging

    # Upload the package to `test.pypi.org` when there is a push to
    # `release/test` branch:
    - stage: "Test deploy"
      deploy:
        provider: pypi
        server: https://test.pypi.org/legacy/
        user: __token__
        password:
          secure: YlT55PlGYZDr1wZNiEiCgFFToyyRixakVhIpuVVOHlU1Mk8jS6ovBwwHlsuKWzkV2OtBStwC5FoOkZs+SwAhFpbZN/W9uL+asknKFZitgVdc8YTyVB0jXtscBEKWEfbvBIzrQe8kSxbUQnk3E5Kg61YmFq5VbGAm0G1XwPI6WExBmaMuNBjGdKcNv85dxRe/yCMVrf3c9lQ14Pl7W/dIxQIC9cPFDykYCmh2F7TKvk2fJPcQ8KTV8/d5okiqB0+m6Q5P59eDxtt+YDah8Nfha0wVHsJaxIJy8GWwmhv7Z75W/pa51/S9vlThrBR2vQKSf2XxWxpVwEj3VJF5By85FG6rdGra23YSg8GgabTZYBpdKFu/RsD2oJ/XajpOiF+GorO8MahsCfupssTX8ca19n7ckCZOjkGwJNcQy3kHiybVHPpSJFdbyDP5tcE5NgB47AV/ELHcLZnLyetq7POIzds6be6er86Pin9pUO6lXxU7HXH9lZG2CQhCRk+wnLUzruzLAvIIrnDn3NNdxWEJVMg0NUAy7pB8+ajSaoVJSj0tRLarmILPLzYRK35O6CWRUxKskqMai568uy+SO0zbMw3dGOCJeQeBTgxpI6ICeihv0007lEYwV3sIavgjTpy2KVTdqwqWxibZ+PjH1nHorh93FP4Ns4PgtvsqmC8oxf0=
        distributions: "sdist bdist_wheel"
        on:
          branch: release/test
          repo: tkf/tkfplaygroundpy
      if: branch = release/test
      script: skip
      after_success:
        - echo "skipped"
        # Do not use `after_success: skip` as it would skip the deploy
        # step.
        # https://github.com/travis-ci/travis-ci/issues/8337#issuecomment-326838809

    # Test uploaded package
    - stage: "Test upload"
      if: branch = release/test OR branch = upload/test
      script:
        - cd ci/test-upload && tox
      after_success: skip
