sudo: false
language: python

python:
  - "2.7"
  - "3.6"

env:
  global:
    # Use the Python version specified by Travis inside tox:
    - TOXENV=py

before_install:
  - pip install --quiet tox coveralls

script:
  - tox -- --cov=tkfplaygroundpy

after_success:
  # Strip off ".tox/..." from the coverage
  # (see also [[./tox.ini::coverage:paths]]):
  - .tox/py*/bin/coverage combine .coverage
  - coveralls

notifications:
  email: false
