sudo: false
language: python
dist: xenial

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - pip install --quiet "pip>=19.0" "setuptools>=41.0"
  - pip install --quiet tox coveralls
  - pip --version
  - tox --version
  - pip freeze --all

script:
  - tox -- --cov=tkfplaygroundpy

after_success:
  # Strip off ".tox/..." from the coverage
  # (see also [[./tox.ini::coverage:paths]]):
  - .tox/py*/bin/coverage combine .coverage
  - coveralls

notifications:
  email: false
