sudo: false
language: python
dist: xenial

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - pip install --quiet --upgrade pip setuptools
  - pip install --quiet --upgrade tox coveralls
  - pip --version
  - tox --version
  - pip freeze

script:
  - tox -- --cov=tkfplaygroundpy

after_success:
  # Strip off ".tox/..." from the coverage
  # (see also [[./tox.ini::coverage:paths]]):
  - .tox/py*/bin/coverage combine .coverage
  - coveralls

notifications:
  email: false
