sudo: false
language: python

python:
  - "3.6"

before_install:
  - pip install --quiet --upgrade pip
  - pip install --quiet --upgrade tox coveralls

script:
  - tox -- --cov=tkfplaygroundpy

after_success:
  # Strip off ".tox/..." from the coverage
  # (see also [[./tox.ini::coverage:paths]]):
  - .tox/py*/bin/coverage combine .coverage
  - coveralls

notifications:
  email: false
